# This workflow checks the entire merge group doesn't have a file caleld
# 'file3'. This si simply for ease of testing merge queues.

name: Merge Group Tests

on:
  merge_group:

jobs:
  merge-group-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a merge group test"
