# This workflow checks the entire merge group doesn't have a file caleld
# 'file3'. This si simply for ease of testing merge queues.

name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the Merge Group
      uses: actions/checkout@v4

    - name: Run Check
      run: |
        if [ -f file3 ]
        then
          exit 1
        fi
