
# This workflow simply checks that a two files called "file1" and "file2" don't
# both exit in the repo root. It's simply a quick way to invoke a failure.

name: Per PR Tests

on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}--${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the PR
      uses: actions/checkout@v4

    - name: Run Check
      run: |
        if [ -f file1 ]
        then
          if [ -f file2 ]
          then
            exit 1
          fi
        fi
